from django.core.validators import RegexValidator

phone_regex = RegexValidator(
    regex=r'^\d{10}$',
    message='error: phone number must be of the form: xxxxxxxxxx (ex. 0723456789)'
)

state_choices = (
    ('AB', 'Alba'),
    ('AR', 'Arad'),
    ('AG', 'Arges'),
    ('B', 'Bucuresti'),
    ('BC', 'Bacau'),
    ('BH', 'Bihor'),
    ('BN', 'Bistrita-Nasaud'),
    ('BT', 'Botosani'),
    ('BR', 'Braila'),
    ('BV', 'Brasov'),
    ('BZ', 'Buzau'),
    ('CL', 'Calarasi'),
    ('CS', 'Caras-Severin'),
    ('CJ', 'Cluj'),
    ('CT', 'Constanta'),
    ('CV', 'Covasna'),
    ('DB', 'Dambovita'),
    ('DJ', 'Dolj'),
    ('GL', 'Galati'),
    ('GR', 'Giurgiu'),
    ('GJ', 'Gorj'),
    ('HR', 'Harghita'),
    ('HD', 'Hunedoara'),
    ('IL', 'Ialomita'),
    ('IS', 'Iasi'),
    ('IF', 'Ilfov'),
    ('MM', 'Maramures'),
    ('MH', 'Mehedinti'),
    ('MS', 'Mures'),
    ('NT', 'Neamt'),
    ('OT', 'Olt'),
    ('PH', 'Prahova'),
    ('SJ', 'Salaj'),
    ('SM', 'Satu Mare'),
    ('SB', 'Sibiu'),
    ('SV', 'Suceava'),
    ('TR', 'Teleorman'),
    ('TM', 'Timis'),
    ('TL', 'Tulcea'),
    ('VL', 'Valcea'),
    ('VS', 'Vaslui'),
    ('VN', 'Vrancea'),
)